### PR TITLE
Update slyguy domain

### PR DESCRIPTION
**Pull request by matthuisman**
trying to work out why my old domain still has a lot of monthly hits.

https://github.com/search?q=https%3A%2F%2Fk.slyguy.xyz%2F&type=Code :(

But this is a start.
All of them duplicating the repo can just deal when we kill that old domain

### CODE REVIEW

**Comment by matthuisman** [comment]
also, fyi - you may want to support aarch64 now

**Comment by glennguy** [comment]
Thanks Matt!

**Comment by matthuisman** [comment]
no worries :) Can you let me know when you release the update to the addon with this change?
Want to monitor the traffic and see if it drops

**Comment by glennguy** [comment]
@matthuisman released last night :)

**Pull request merged**
